#include "gps.h"

#include <string.h>
#include <stdlib.h>


/*
 * DMA reception buffer.
 *
 * UART DMA writes received bytes into this buffer.
 */
#define GPS_DMA_BUFFER_SIZE       128U


/*
 * Software ring buffer.
 *
 * The UART callback writes bytes here.
 * GPS_Process() reads bytes from here.
 */
#define GPS_RING_BUFFER_SIZE      512U


/*
 * Maximum supported NMEA sentence length,
 * including the null terminator.
 */
#define GPS_SENTENCE_BUFFER_SIZE  128U


/*
 * Private GPS data structure.
 *
 * It can only be modified directly inside gps.c.
 */
static GPS_Data_t gps_data;


/*
 * UART used by the GPS module.
 */
static UART_HandleTypeDef *gps_huart = NULL;


/*
 * DMA reception buffer.
 */
static uint8_t gps_dma_buffer[GPS_DMA_BUFFER_SIZE];


/*
 * Software ring buffer.
 */
static uint8_t gps_ring_buffer[GPS_RING_BUFFER_SIZE];

static volatile uint16_t gps_ring_head = 0U;
static volatile uint16_t gps_ring_tail = 0U;

static volatile bool gps_ring_overflow = false;


/*
 * Buffer used to assemble one complete NMEA sentence.
 */
static char gps_sentence_buffer[GPS_SENTENCE_BUFFER_SIZE];

static uint16_t gps_sentence_index = 0U;
static bool gps_sentence_started = false;


/*
 * Private function declarations.
 */
static GPS_Status_t GPS_StartDMAReception(void);

static bool GPS_RingBufferWrite(uint8_t data);

static bool GPS_RingBufferRead(uint8_t *data);

static bool GPS_GetField(const char *sentence,
                         uint8_t field_index,
                         char *output,
                         uint16_t output_size);

static bool GPS_ConvertCoordinate(const char *coordinate,
                                  char direction,
                                  float *decimal_degrees);

static bool GPS_ValidateChecksum(const char *sentence);

static int8_t GPS_HexToValue(char character);

static void GPS_ResetSentenceAssembly(void);

static void GPS_HandleRingBufferOverflow(void);


/*
 * Initializes the GPS driver.
 */
GPS_Status_t GPS_Init(UART_HandleTypeDef *huart)
{
    if (huart == NULL)
    {
        return GPS_STATUS_ERROR;
    }

    gps_huart = huart;

    gps_data.latitude_deg  = 0.0f;
    gps_data.longitude_deg = 0.0f;
    gps_data.altitude_m    = 0.0f;

    gps_data.fix_valid = false;
    gps_data.new_data  = false;

    gps_ring_head = 0U;
    gps_ring_tail = 0U;

    gps_ring_overflow = false;

    GPS_ResetSentenceAssembly();

    return GPS_StartDMAReception();
}


/*
 * Starts UART reception using DMA and idle-line detection.
 */
static GPS_Status_t GPS_StartDMAReception(void)
{
    HAL_StatusTypeDef hal_status;

    if (gps_huart == NULL)
    {
        return GPS_STATUS_ERROR;
    }

    hal_status = HAL_UARTEx_ReceiveToIdle_DMA(
        gps_huart,
        gps_dma_buffer,
        GPS_DMA_BUFFER_SIZE
    );

    if (hal_status != HAL_OK)
    {
        return GPS_STATUS_ERROR;
    }

    /*
     * Disable the DMA half-transfer interrupt.
     *
     * We only need UART IDLE and DMA transfer-complete
     * reception events.
     */
    if (gps_huart->hdmarx != NULL)
    {
        __HAL_DMA_DISABLE_IT(gps_huart->hdmarx,
                             DMA_IT_HT);
    }

    return GPS_STATUS_OK;
}


/*
 * Receives the UART DMA event from the HAL callback.
 *
 * This function only copies bytes into the software
 * ring buffer. It does not parse GPS messages.
 */
void GPS_UART_RxEventCallback(UART_HandleTypeDef *huart,
                              uint16_t received_size)
{
    uint16_t index;

    /*
     * Ignore events generated by another UART.
     */
    if ((huart == NULL) || (huart != gps_huart))
    {
        return;
    }

    /*
     * Protect against an invalid received size.
     */
    if (received_size > GPS_DMA_BUFFER_SIZE)
    {
        received_size = GPS_DMA_BUFFER_SIZE;
    }

    /*
     * Copy the received DMA bytes into the
     * software ring buffer.
     */
    for (index = 0U; index < received_size; index++)
    {
        if (!GPS_RingBufferWrite(gps_dma_buffer[index]))
        {
            gps_ring_overflow = true;

            /*
             * The ring buffer is full.
             * The remaining bytes from this event
             * are discarded.
             */
            break;
        }
    }

    /*
     * Restart DMA reception for the next GPS bytes.
     */
    if (GPS_StartDMAReception() != GPS_STATUS_OK)
    {
        /*
         * Reception could not be restarted.
         *
         * A UART error-recovery mechanism can be
         * added later if required.
         */
    }
}


/*
 * Writes one byte into the software ring buffer.
 */
static bool GPS_RingBufferWrite(uint8_t data)
{
    uint16_t next_head;

    next_head = gps_ring_head + 1U;

    if (next_head >= GPS_RING_BUFFER_SIZE)
    {
        next_head = 0U;
    }

    /*
     * If the next head position reaches the tail,
     * the ring buffer is full.
     */
    if (next_head == gps_ring_tail)
    {
        return false;
    }

    gps_ring_buffer[gps_ring_head] = data;

    gps_ring_head = next_head;

    return true;
}


/*
 * Reads one byte from the software ring buffer.
 */
static bool GPS_RingBufferRead(uint8_t *data)
{
    if (data == NULL)
    {
        return false;
    }

    /*
     * Head equal to tail means that the buffer is empty.
     */
    if (gps_ring_head == gps_ring_tail)
    {
        return false;
    }

    *data = gps_ring_buffer[gps_ring_tail];

    gps_ring_tail++;

    if (gps_ring_tail >= GPS_RING_BUFFER_SIZE)
    {
        gps_ring_tail = 0U;
    }

    return true;
}


/*
 * Handles a software ring-buffer overflow.
 *
 * When bytes are lost, the current sentence may be
 * incomplete. Therefore, all pending bytes and the
 * current sentence are discarded.
 */
static void GPS_HandleRingBufferOverflow(void)
{
    uint32_t interrupt_state;

    if (!gps_ring_overflow)
    {
        return;
    }

    interrupt_state = __get_PRIMASK();

    __disable_irq();

    gps_ring_tail = gps_ring_head;
    gps_ring_overflow = false;

    if (interrupt_state == 0U)
    {
        __enable_irq();
    }

    GPS_ResetSentenceAssembly();
}


/*
 * Processes bytes received from the GPS module.
 *
 * Call this repeatedly inside the main loop.
 */
void GPS_Process(void)
{
    uint8_t received_byte;

    GPS_HandleRingBufferOverflow();

    while (GPS_RingBufferRead(&received_byte))
    {
        /*
         * Every NMEA sentence starts with '$'.
         *
         * Receiving another '$' also restarts sentence
         * assembly in case a previous sentence was damaged.
         */
        if (received_byte == '$')
        {
            gps_sentence_started = true;
            gps_sentence_index   = 0U;

            gps_sentence_buffer[gps_sentence_index] = '$';
            gps_sentence_index++;

            continue;
        }

        /*
         * Ignore bytes until the beginning of an
         * NMEA sentence is detected.
         */
        if (!gps_sentence_started)
        {
            continue;
        }

        /*
         * Carriage return is not stored.
         */
        if (received_byte == '\r')
        {
            continue;
        }

        /*
         * Line feed marks the end of the NMEA sentence.
         */
        if (received_byte == '\n')
        {
            gps_sentence_buffer[gps_sentence_index] = '\0';

            GPS_ParseSentence(gps_sentence_buffer);

            GPS_ResetSentenceAssembly();

            continue;
        }

        /*
         * Store the received byte if enough space remains.
         */
        if (gps_sentence_index <
            (GPS_SENTENCE_BUFFER_SIZE - 1U))
        {
            gps_sentence_buffer[gps_sentence_index] =
                (char)received_byte;

            gps_sentence_index++;
        }
        else
        {
            /*
             * The sentence exceeded the buffer size.
             * Discard it and wait for the next '$'.
             */
            GPS_ResetSentenceAssembly();
        }
    }
}


/*
 * Resets the NMEA sentence-assembly variables.
 */
static void GPS_ResetSentenceAssembly(void)
{
    gps_sentence_index   = 0U;
    gps_sentence_started = false;

    gps_sentence_buffer[0] = '\0';
}


/*
 * Parses one complete GGA sentence.
 */
bool GPS_ParseSentence(const char *sentence)
{
    char message_type[8];

    char latitude_text[20];
    char latitude_direction[2];

    char longitude_text[20];
    char longitude_direction[2];

    char fix_quality_text[4];
    char altitude_text[20];

    char *conversion_end;

    unsigned long fix_quality;

    float latitude_deg;
    float longitude_deg;
    float altitude_m;


    if (sentence == NULL)
    {
        return false;
    }


    /*
     * Do not use a sentence whose NMEA checksum
     * is incorrect.
     */
    if (!GPS_ValidateChecksum(sentence))
    {
        return false;
    }


    /*
     * Extract field zero, which contains the
     * NMEA message type.
     */
    if (!GPS_GetField(sentence,
                      0U,
                      message_type,
                      sizeof(message_type)))
    {
        return false;
    }


    /*
     * A normal NMEA message name contains:
     *
     * '$' + two talker characters + three message characters
     *
     * Examples:
     *
     * $GNGGA
     * $GPGGA
     *
     * Checking the last three characters allows different
     * GNSS talker identifiers while accepting only GGA.
     */
    if ((strlen(message_type) != 6U) ||
        (strcmp(&message_type[3], "GGA") != 0))
    {
        return false;
    }


    /*
     * Extract fix quality first.
     *
     * GGA field 6:
     *
     * 0 = No valid position fix
     * Greater than zero = Position fix available
     */
    if (!GPS_GetField(sentence,
                      6U,
                      fix_quality_text,
                      sizeof(fix_quality_text)))
    {
        return false;
    }


    fix_quality = strtoul(fix_quality_text,
                         &conversion_end,
                         10);


    if ((conversion_end == fix_quality_text) ||
        (*conversion_end != '\0'))
    {
        return false;
    }


    /*
     * Fix quality zero means that the current position
     * values must not be used.
     */
    if (fix_quality == 0UL)
    {
        gps_data.fix_valid = false;
        gps_data.new_data  = true;

        return true;
    }


    /*
     * Extract latitude.
     *
     * GGA field 2:
     * ddmm.mmmmm
     */
    if (!GPS_GetField(sentence,
                      2U,
                      latitude_text,
                      sizeof(latitude_text)))
    {
        return false;
    }


    /*
     * Extract latitude direction.
     *
     * GGA field 3:
     * N or S
     */
    if (!GPS_GetField(sentence,
                      3U,
                      latitude_direction,
                      sizeof(latitude_direction)))
    {
        return false;
    }


    /*
     * The direction field must contain exactly
     * one character.
     */
    if (latitude_direction[1] != '\0')
    {
        return false;
    }


    /*
     * Extract longitude.
     *
     * GGA field 4:
     * dddmm.mmmmm
     */
    if (!GPS_GetField(sentence,
                      4U,
                      longitude_text,
                      sizeof(longitude_text)))
    {
        return false;
    }


    /*
     * Extract longitude direction.
     *
     * GGA field 5:
     * E or W
     */
    if (!GPS_GetField(sentence,
                      5U,
                      longitude_direction,
                      sizeof(longitude_direction)))
    {
        return false;
    }


    if (longitude_direction[1] != '\0')
    {
        return false;
    }


    /*
     * Extract altitude above mean sea level.
     *
     * GGA field 9:
     * Altitude in metres.
     */
    if (!GPS_GetField(sentence,
                      9U,
                      altitude_text,
                      sizeof(altitude_text)))
    {
        return false;
    }


    /*
     * Convert the NMEA latitude to decimal degrees.
     */
    if (!GPS_ConvertCoordinate(latitude_text,
                               latitude_direction[0],
                               &latitude_deg))
    {
        return false;
    }


    /*
     * Convert the NMEA longitude to decimal degrees.
     */
    if (!GPS_ConvertCoordinate(longitude_text,
                               longitude_direction[0],
                               &longitude_deg))
    {
        return false;
    }


    /*
     * Convert altitude text to a floating-point value.
     */
    altitude_m = strtof(altitude_text,
                        &conversion_end);


    if ((conversion_end == altitude_text) ||
        (*conversion_end != '\0'))
    {
        return false;
    }


    /*
     * Update the GPS data only after all required
     * fields have been successfully validated.
     */
    gps_data.latitude_deg  = latitude_deg;
    gps_data.longitude_deg = longitude_deg;
    gps_data.altitude_m    = altitude_m;

    gps_data.fix_valid = true;
    gps_data.new_data  = true;

    return true;
}


/*
 * Extracts one field from an NMEA sentence.
 *
 * Field numbering starts from zero.
 *
 * Example:
 *
 * $GNGGA,123519.00,4101.23456,N,...
 *
 * Field 0 = $GNGGA
 * Field 1 = 123519.00
 * Field 2 = 4101.23456
 * Field 3 = N
 */
static bool GPS_GetField(const char *sentence,
                         uint8_t field_index,
                         char *output,
                         uint16_t output_size)
{
    const char *field_start;
    const char *field_end;
    const char *comma_position;

    uint8_t current_field;
    uint16_t field_length;


    if ((sentence == NULL) ||
        (output == NULL) ||
        (output_size == 0U))
    {
        return false;
    }


    field_start   = sentence;
    current_field = 0U;


    /*
     * Move through the comma-separated fields
     * until the requested field is reached.
     */
    while (current_field < field_index)
    {
        comma_position = strchr(field_start, ',');

        if (comma_position == NULL)
        {
            return false;
        }

        field_start = comma_position + 1;

        current_field++;
    }


    /*
     * Find the end of the selected field.
     */
    field_end = field_start;

    while ((*field_end != '\0') &&
           (*field_end != ',')  &&
           (*field_end != '*')  &&
           (*field_end != '\r') &&
           (*field_end != '\n'))
    {
        field_end++;
    }


    field_length =
        (uint16_t)(field_end - field_start);


    /*
     * The destination must have enough space for
     * the field and the null terminator.
     */
    if (field_length >= output_size)
    {
        return false;
    }


    memcpy(output,
           field_start,
           field_length);


    output[field_length] = '\0';


    return true;
}


/*
 * Converts an NMEA coordinate to decimal degrees.
 *
 * Example:
 *
 * 4101.23456,N
 *
 * Degrees = 41
 * Minutes = 01.23456
 *
 * Decimal degrees:
 *
 * 41 + 1.23456 / 60
 */
static bool GPS_ConvertCoordinate(const char *coordinate,
                                  char direction,
                                  float *decimal_degrees)
{
    char *conversion_end;

    float raw_coordinate;
    float minutes;
    float converted_coordinate;
    float maximum_degrees;

    uint16_t degrees;


    if ((coordinate == NULL) ||
        (decimal_degrees == NULL) ||
        (coordinate[0] == '\0'))
    {
        return false;
    }


    /*
     * Validate the direction.
     */
    if ((direction != 'N') &&
        (direction != 'S') &&
        (direction != 'E') &&
        (direction != 'W'))
    {
        return false;
    }


    raw_coordinate = strtof(coordinate,
                            &conversion_end);


    if ((conversion_end == coordinate) ||
        (*conversion_end != '\0'))
    {
        return false;
    }


    /*
     * The NMEA coordinate itself must be positive.
     * The sign is determined by N, S, E or W.
     */
    if (raw_coordinate < 0.0f)
    {
        return false;
    }


    degrees =
        (uint16_t)(raw_coordinate / 100.0f);


    minutes =
        raw_coordinate -
        ((float)degrees * 100.0f);


    /*
     * Coordinate minutes must be less than 60.
     */
    if ((minutes < 0.0f) ||
        (minutes >= 60.0f))
    {
        return false;
    }


    /*
     * Select the maximum possible coordinate.
     */
    if ((direction == 'N') ||
        (direction == 'S'))
    {
        maximum_degrees = 90.0f;
    }
    else
    {
        maximum_degrees = 180.0f;
    }


    converted_coordinate =
        (float)degrees +
        (minutes / 60.0f);


    if (converted_coordinate > maximum_degrees)
    {
        return false;
    }


    /*
     * South and West coordinates are negative.
     */
    if ((direction == 'S') ||
        (direction == 'W'))
    {
        converted_coordinate =
            -converted_coordinate;
    }


    *decimal_degrees = converted_coordinate;


    return true;
}


/*
 * Validates the checksum of an NMEA sentence.
 *
 * Example:
 *
 * $GNGGA,...*75
 *
 * The checksum is calculated by XORing all characters
 * located between '$' and '*'.
 */
static bool GPS_ValidateChecksum(const char *sentence)
{
    const char *checksum_position;
    const char *character;

    uint8_t calculated_checksum;
    uint8_t received_checksum;

    int8_t high_nibble;
    int8_t low_nibble;


    if ((sentence == NULL) ||
        (sentence[0] != '$'))
    {
        return false;
    }


    checksum_position = strchr(sentence, '*');

    if (checksum_position == NULL)
    {
        return false;
    }


    /*
     * Two hexadecimal characters must follow '*'.
     */
    if ((checksum_position[1] == '\0') ||
        (checksum_position[2] == '\0'))
    {
        return false;
    }


    high_nibble = GPS_HexToValue(checksum_position[1]);
    low_nibble  = GPS_HexToValue(checksum_position[2]);


    if ((high_nibble < 0) ||
        (low_nibble < 0))
    {
        return false;
    }


    received_checksum =
        (uint8_t)(((uint8_t)high_nibble << 4U) |
                   (uint8_t)low_nibble);


    calculated_checksum = 0U;


    /*
     * Skip the initial '$'.
     */
    character = sentence + 1;


    while (character < checksum_position)
    {
        calculated_checksum ^=
            (uint8_t)(*character);

        character++;
    }


    return calculated_checksum == received_checksum;
}


/*
 * Converts one hexadecimal character into
 * its numerical value.
 */
static int8_t GPS_HexToValue(char character)
{
    if ((character >= '0') &&
        (character <= '9'))
    {
        return (int8_t)(character - '0');
    }

    if ((character >= 'A') &&
        (character <= 'F'))
    {
        return (int8_t)(character - 'A' + 10);
    }

    if ((character >= 'a') &&
        (character <= 'f'))
    {
        return (int8_t)(character - 'a' + 10);
    }

    return -1;
}


/*
 * Returns a read-only pointer to the latest GPS data.
 */
const GPS_Data_t *GPS_GetData(void)
{
    return &gps_data;
}


/*
 * Returns the current GPS fix state.
 */
bool GPS_IsFixValid(void)
{
    return gps_data.fix_valid;
}


/*
 * Returns true when new valid GPS data is available.
 */
bool GPS_IsNewDataAvailable(void)
{
    return gps_data.new_data;
}


/*
 * Clears the new-data flag.
 */
void GPS_ClearNewDataFlag(void)
{
    gps_data.new_data = false;
}